### ISSUE TITLE
No timeout or options in dial()

### ISSUE THREAD

**Issue by gfelisberto** [asterisk-java/asterisk-java#130] opened 2016-04-18 08:52 UTC
Hello,

I'm running the head version of asterisk-java with asterisk 13.7.1.

In my AGI if I use:
dial(“SIP/2”, 20, “m”)

I get in the Java STDOUT: EXEC "dial" "SIP/2" "30" "m"
But in the Asterisk console: [2016-04-15 18:28:55] VERBOSE[9941][C-0000003e] res_agi.c: AGI Script Executing Application: (dial) Options: (SIP/2)

And if in my AGI I do:
channel.exec("DIAL", "SIP/2,30,m");

In the Asterisk console I get: [2016-04-15 18:32:54] VERBOSE[10298][C-0000003f] res_agi.c: AGI Script Executing Application: (DIAL) Options: (SIP/2,30,m)

It seems the options (timeout and others) are being lost somewhere.

**Comment by bsutton** [comment] 2016-04-18 11:05
You will need to provide some sample code as your explanation isn't very 
clear to me at least.

**Comment by gfelisberto** [comment] 2016-04-18 14:25
Hello,


public class SampleAGI extends BaseAgiScript{

	@Override
	public void service(AgiRequest request, AgiChannel channel) throws AgiException {
		answer();
		
		//If I use this it dials the target and caller listens to music on hold, after 30 seconds of ringing it stops trying
		//Asterisk console reports that the command sent was: AGI Script Executing Application: (DIAL) Options: (SIP/2,30,m)
		channel.exec("DIAL", "SIP/2,30,m");
	
		//If i use this one it will dial the target, no music on hold is played to caller and it keeps ringing for ever.
		//Asterisk console reports that the command sent was: AGI Script Executing Application: (dial) Options: (SIP/2)
		dial("SIP/2", 30, "m");	
		hangup();
	}
}

**Comment by bsutton** [comment] 2016-04-18 22:07
So the issue is that the dial() function doesn't put comma's between the 
parameters.

The problem is that I'm wondering why this hasn't been picked up before?

What version of asterisk are you using?

Has anyone else on the list used the BaseAgeScript.dial function before 
with options?

The fix is easy I just don't want to break peoples systems if it is 
currently working on other version of asterisk and I'm having trouble 
finding a clear history of the dial command on different versions of 
asterisk.

Brett

**Comment by gfelisberto** [comment] 2016-04-19 08:37
I'm running Asterisk 13.7.1. The documentation for the dial states that it should be with comma's. 

I tracked down an old project (2008-10) and there I used the comma's to separate options in dial. Unfortunately I do not have information on the Asterisk version used there.

**Comment by bsutton** [comment] 2016-04-19 10:49
So I've commited an untested patch to master.

Can you test it and let me know how it went.

Brett

**Comment by gfelisberto** [comment] 2016-04-19 13:53
Could not find your commit. [Here](https://github.com/gfelisberto/asterisk-java/commit/2b1927626924015d6e7f7d93cba054ec702a3e64) is my patch:

**Comment by bsutton** [comment] 2016-05-23 23:07
patch from gfelisberto has been merged.

**Closed by bsutton** 2016-05-23 23:07 UTC
