### ISSUE TITLE
Cannot handle disconnect events (Glassfish 4.1)

### ISSUE THREAD

**Issue by elettrico** [asterisk-java/asterisk-java#199] opened 2017-05-29 15:37 UTC
Hi, I'm using asterisk-java version 1.1.0 inside a glassfish environment.
In my code I have a singleton EJB:

```
@Singleton
@LocalBean
@ConcurrencyManagement(ConcurrencyManagementType.CONTAINER)
@Lock(LockType.READ)
public class TServer implements
        AsteriskServerListener,
        AsteriskQueueListener,
        ManagerEventListener,
        PropertyChangeListener,
        TServerLocal {
  [...]
  // servidores
  private HashMap<String, AsteriskServer> asteriskServers = new HashMap<>();
  [...]
  @Override
  public TServerConnectionStatus connect(String hostname, String username, String password) {
    if (this.asteriskServers.containsKey(hostname)) {
      return this.getConnectionStatus(hostname);
    }
    AsteriskServer asteriskServer = new DefaultAsteriskServer(hostname, username, password);
    asteriskServer.addAsteriskServerListener(this);
    asteriskServer.getManagerConnection().addEventListener(this);
    return this.getConnectionStatus(hostname);
  }
  [...]
}
```

When I connect to an asterisk server I pass the singleton as listener, all events works perfectly and I have no problem at all, until a disconnection or timeout: when asterisk-java disconnect from the pbx I cannot intercept the event and so I cannot issue a reconnection, instead I start to have errors in the log:

```
[2017-05-25T16:42:36.804-0300] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=680 _ThreadName=Thread-9] [timeMillis: 1495741356804] [levelValue: 1000] [[
  Exception in thread "AJ DaemonPool-2.1"]]

[2017-05-25T16:42:36.812-0300] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=680 _ThreadName=Thread-9] [timeMillis: 1495741356812] [levelValue: 1000] [[
  org.asteriskjava.live.ManagerCommunicationException: Unable to send GetVarAction
        at org.asteriskjava.live.internal.ManagerCommunicationExceptionMapper.mapSendActionException(ManagerCommunicationExceptionMapper.java:60)
        at org.asteriskjava.live.internal.AsteriskServerImpl.sendAction(AsteriskServerImpl.java:957)
        at org.asteriskjava.live.internal.AsteriskChannelImpl.getVariable(AsteriskChannelImpl.java:695)
        at org.asteriskjava.live.internal.ChannelManager.addNewChannel(ChannelManager.java:221)
        at org.asteriskjava.live.internal.ChannelManager.handleNewChannelEvent(ChannelManager.java:494)
        at org.asteriskjava.live.internal.AsteriskServerImpl.onManagerEvent(AsteriskServerImpl.java:1015)
        at org.asteriskjava.manager.ManagerEventListenerProxy$1.run(ManagerEventListenerProxy.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.asteriskjava.manager.TimeoutException: Timeout waiting for response to GetVar
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.sendAction(ManagerConnectionImpl.java:922)
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.sendAction(ManagerConnectionImpl.java:877)
        at org.asteriskjava.manager.DefaultManagerConnection.sendAction(DefaultManagerConnection.java:311)
        at org.asteriskjava.live.internal.AsteriskServerImpl.sendAction(AsteriskServerImpl.java:953)
        ... 8 more]]
```

Every subsequent call get "queued" in a "AJ DaemonPool" (I imagine) using 100% of the cpu, until I stop/restart glassfish. I think more threads are spawned while the others are waiting for a timeout, but I don't know if it's as intended and where I can configure how many threads can be launched.
Also I don't understand how I can get notified about the timeout/disconnection or if I'm using the wrong approach.
I think something strange is happening at thread level but as in Glassfish environment I cannot (and shouldn't) control threads directly.

**Comment by bsutton** [comment] 2017-08-28 02:27
sorry for the late reply, but we would need to see the rest of the stack trace to see what is generating the sendaction.

And when you use asterisk java you will need to understand the threading. 
Glassfish will manage the web service threads but the rest are yours to manage.

**Comment by elettrico** [comment] 2017-09-07 20:24
Sorry for the late response.

I'm not sure what you say about Glassfish, as far I know an application server manage the threading and bean instances, and it's discouraged to manage threads directly to not interfere with the container management, it isn't only a web server. I'm using AJ inside a singleton bean so thread management and concurrency will be managed by glassfish.

The paste above is the stacktrace I have in the log, generally I have this kind of errors when the connection to the pbx is lost, for example because of a network error:
```
Caused by: org.asteriskjava.live.ManagerCommunicationException: Unable to send CommandAction
        at org.asteriskjava.live.internal.ManagerCommunicationExceptionMapper.mapSendActionException(ManagerCommunicationExceptionMapper.java:60)
        at org.asteriskjava.live.internal.AsteriskServerImpl.sendAction(AsteriskServerImpl.java:957)
        at org.asteriskjava.live.internal.AsteriskServerImpl.executeCliCommand(AsteriskServerImpl.java:776)
        at org.asteriskjava.live.DefaultAsteriskServer.executeCliCommand(DefaultAsteriskServer.java:265)
        at com.tecytal.crm.tyterisk.TServer.isDndActive(TServer.java:460)
        at sun.reflect.GeneratedMethodAccessor1022.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:46)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        ... 147 more
Caused by: org.asteriskjava.manager.TimeoutException: Timeout waiting for response to Command
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.sendAction(ManagerConnectionImpl.java:922)
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.sendAction(ManagerConnectionImpl.java:877)
        at org.asteriskjava.manager.DefaultManagerConnection.sendAction(DefaultManagerConnection.java:311)
        at org.asteriskjava.live.internal.AsteriskServerImpl.sendAction(AsteriskServerImpl.java:953)
        ... 178 more
]]
```
the point is that when this occur I don't receive any event (for example to force disconnection and reconnection) and sometime threads keep sending command and waiting for response.
What is the correct behaviour in case, for example, of a network shortage? How can I detect the loss of connectivity with the PBX?

Thank you

**Comment by bsutton** [comment] 2017-09-08 01:34
The idea that you don't manage your own threads is correct if you building simple websites that just serve up pages. 
As soon as you start talking to a process like asterisk then you are playing in a different league and will need to manage your own threads.
As to the disconnect, asterisk-java will auto reconnect but this will take a number of seconds. You should expect to see a series of errors (such as the one you logged) until the system reconnects.
You should probably monitor the disconnect events emmited by asterisk-java and stop all interaction with asterisk until you get the connect event.

**Comment by elettrico** [comment] 2017-11-07 18:20
Thank for your reply.

"You should probably monitor the disconnect events emmited by asterisk-java" -> I absolutely agree with you, the point is of this issue as you can see is "cannot handle disconnect event":

- I do not receive disconnection events, so I cannot manage when send or not commands
- when I send commands to a disconnected PBX I get errors logged like "Actions may only be sent when in state CONNECTED, but connection is in state RECONNECTING" (it's ok, of course) but threads get somewhat stuck, so they start use all cpu and start a thread multiplication: I've ended with more than 200 "AJ DaemonPool" threads

I think it's not normal, I don't know if asterisk-java is not suited to work in an EE environment or if there's a bug, but generating >200 threads and using all cpu time seems a bug to me.

**Comment by elettrico** [comment] 2017-11-07 18:23
This is the code where I try to catch Disconnection events, maybe this isn't the correct way.
```
  @Override
  public void onManagerEvent(ManagerEvent event) {
    //
    if (event instanceof DisconnectEvent) {
        [...]
    }
}
```
the code inside the if is never executed on disconnection.

**Comment by bsutton** [comment] 2017-11-07 20:06
The connection manager automatically re connects.

The it's no point processing disconnect events because even if you did you
can still send an action just as the system is disconnecting.

So the problem is with your code.

You must always be prepared to handle a failed action.

If your threads are looping its a bug in your code.

Asterisk java is well suited to an ee environment. But your code is going
to need more work.

Have a look are the activities in V2.0
 As they provide a high level abstraction for many common asterisk actions.

If your asterisk server is disconnecting a lot you need to check that you
are handling events in a timely manner. If you can't use activities look at
the coherentevent manager as it detaches your thread from the event
receiver which may reduce the no of disconnects. Asterisk will disconnect
you if you don't process events in a timely manner.

There is also a timeout setting in the asterisk manager settings which can
help if you increase it.

**Comment by elettrico** [comment] 2017-11-07 21:52
I apologize if I sound pedantic, but I'm pretty sure my code is not the problem. Not because I'm the best programmer in the world :) but because I've reduced it to a very basic code and the problem persist. 

I do not have loops, I do not generate or manipulate thread in any way. If you've read the pastebin I've pasted above, you can see how AJ DaemonPool threads are growing for every action placed on a disconnected pbx, and of course I'm not creating those threads.

Actually I have a Java EE application with a Singleton EJB and a webservice inside, when the application starts the application server instance the singleton and it connect to asterisk using this very simple method:
```
public void connect(String hostname, String username, String password) {
	this.asteriskServer = new DefaultAsteriskServer(hostname, username, password);
	this.asteriskServer.addAsteriskServerListener(this);
	this.asteriskServer.getManagerConnection().addEventListener(this);
}

```
then I've a method for placing a call, this method is called from the webservice:
```
public String call(String user, String number, int timeout) {
	//
    String context = "from-internal";
    String channelTo = "Local/" + number + "@" + context;
    String channelFrom = "SIP/" + user;
	//
    // originate
    OriginateAction originateAction;
    originateAction = new OriginateAction();
    originateAction.setChannel(channelFrom);
    originateAction.setContext(context);
    originateAction.setPriority(1);
    originateAction.setTimeout(1000L * timeout);
    originateAction.setExten(number);
    originateAction.setCallerId(user);
    try {
		// asteriskServer is the asterisk-java instance
		AsteriskChannel asteriskChannel = this.asteriskServer.originate(originateAction);
		// monitor the resulting channel
		this.monitorChannel(asteriskChannel);
		return asteriskChannel.getId();
    } catch (ManagerCommunicationException | NoSuchChannelException ex) {
		return null;
    }
}

```
the other methods in the singleton are listening to events but the only thing they actually do is log them.
I cannot simplify more my code (if you see something strange in these lines I'm grateful if you point me at it).

Everything works fine for days or weeks, lot of calls are placed without problem. 
I have no disconnection logged, but sometimes apparently the connection goes down, AJ get stuck in "reconnecting" state (and never reconnect, until I manually restart the application) and every originate create an exception in a new AJ DaemonPool thread.
I'm sorry but I haven't found a pattern, sometimes simply is a "bad day" and I have to restart the app two or three times.

I'll try to see if changing timeout or maybe a pingthread can get rid of the disconnection. I hope I can provide more details.

**Comment by bsutton** [comment] 2017-11-07 22:58
Are you using the very latest verison from 'master'.

There were some race conditions identified recently with reconnects 
which master contains fixes for.

Have you done a thread dump to see what the churning threads are doing?

Why are you doing a local dial. Generally we avoid these like the plauge 
they are dangerous.

These days we run with about 8 lines of dial plan. Everything else we do 
via AGI and Activities.

Did you know you can originate directly into an 'agi'? This is really 
powerful and what we used to eliminate dialplan.

Dialplan is also extremely slow. You will handle a much large volume of 
calls on a given system if you do everything with agi.


Use an activity instead.

I've just added some additional examples:

https://github.com/asterisk-java/asterisk-java/wiki/Examples

Also read:

https://github.com/asterisk-java/asterisk-java/wiki/Getting-Started

https://github.com/asterisk-java/asterisk-java/wiki/Tutorial

https://github.com/asterisk-java/asterisk-java/wiki/Activities


Activities make everything simpler.

**Comment by elettrico** [comment] 2017-11-08 00:45
I'm still running version 1.1. It's safe to use master branch in production?
Anyway, I'll try all your suggestions.

**Comment by bsutton** [comment] 2018-05-06 00:31
closed as no further activity.

**Closed by bsutton** 2018-05-06 00:31 UTC
