### ISSUE TITLE
Unable to set property 'cause' to '18'

### ISSUE THREAD

**Issue by argj** [asterisk-java/asterisk-java#163] opened 2016-08-18 22:09 UTC
2016-08-18 17:50:20,847 WARN [org.asteriskjava.manager.internal.EventBuilderImpl] - <Unable to set property 'cause' to '18' on org.asteriskjava.manager.event.HangupRequestEvent: no setter. Please report at http://jira.reucon.org/browse/AJ> ()

**Comment by seanbright** [comment] 2018-01-30 12:51
Duplicate of #162

**Closed by seanbright** 2018-01-30 12:51 UTC
