### ISSUE TITLE
Issues implementing Phonebridge that uses Asterisk-Java

### ISSUE THREAD

**Issue by choiceit** [asterisk-java/asterisk-java#120] opened 2016-04-05 15:21 UTC
Hi guys!

Please let me know if this is not the correct place to ask for help with this!

I am trying to get an application called Zoho Phonebridge working. Currently, making outgoing calls from the Zoho CRM are working just fine. However, one of the features of this phone bridge is a popup web browser notification when an incoming call comes in that has the same inbound CID as a 'record' in the CRM.

I am getting these error messages (I have replaced phone numbers with'xxxxxxxxx':

`SEVERE: Unable to set property 'rtt' to '0.1570' on org.asteriskjava.manager.event.RtcpReceivedEvent
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.asteriskjava.manager.internal.AbstractBuilder.setAttributes(AbstractBuilder.java:122)
        at org.asteriskjava.manager.internal.EventBuilderImpl.buildEvent(EventBuilderImpl.java:282)
        at org.asteriskjava.manager.internal.ManagerReaderImpl.buildEvent(ManagerReaderImpl.java:341)
        at org.asteriskjava.manager.internal.ManagerReaderImpl.run(ManagerReaderImpl.java:217)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "0.1570"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at org.asteriskjava.manager.event.AbstractRtcpEvent.secStringToLong(AbstractRtcpEvent.java:101)
        at org.asteriskjava.manager.event.RtcpReceivedEvent.setRtt(RtcpReceivedEvent.java:202)
        ... 9 more

Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'sentoctets' to '2390080' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0iajitter' to '0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'to' to '[::1]:0' on org.asteriskjava.manager.event.RtcpReceivedEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'linkedid' to '1459787394.5661' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0lsr' to '0' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'calleridname' to 'CH:FRESNO CA' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'pt' to '200(SR)' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'channel' to 'SIP/cbeyond-in-0000112b' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'language' to 'en' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0sourcessrc' to '0x76f10def' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'exten' to 's' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0dlsr' to '0.0000' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'calleridnum' to 'xxxxxxxxxx' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'context' to 'macro-dial' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'from' to '[::1]:0' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'connectedlinenum' to '304' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'uniqueid' to '1459787394.5661' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'channelstatedesc' to 'Up' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'reportcount' to '1' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0cumulativelost' to '0' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0sequencenumbercycles' to '1' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'ssrc' to '0x1d8bebbb' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'connectedlinename' to 'Joe' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'priority' to '17' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0highestsequence' to '16009' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'channelstate' to '6' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0fractionlost' to '0' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
Apr 04, 2016 10:36:11 AM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'report0iajitter' to '1' on org.asteriskjava.manager.event.RtcpSentEvent: no setter. Please report at http://jira.reucon.org/browse/AJ`

**Comment by bsutton** [comment] 2016-04-06 01:33
Generally 'unable to set property' messages can be ignored.

This particular on is a bit more problematic but it won't be the cause 
of your problem.

Please report is as a bug on git hub.
Make certain you report the asterisk version.

As to your zoho phone bridge problem you will need to talk to the 
developers.

**Comment by bsutton** [comment] 2016-04-06 23:17
I'm closing this issues as its a duplicate of #117

**Closed by bsutton** 2016-04-06 23:17 UTC
