### ISSUE TITLE
Problem: manager not reconnecting to asterisk

### ISSUE THREAD

**Issue by kostyanx** [asterisk-java/asterisk-java#121] opened 2016-04-06 07:54 UTC
please help

**Comment by bsutton** [comment] 2016-04-06 23:19
Closed as not an issue. Advise submitter to post questions on the user list.

**Closed by bsutton** 2016-04-06 23:19 UTC

**Comment by bsutton** [comment] 2016-04-07 01:37
Your not going to get any help with that level of information.

Think a little more deeply about the problem and then post your question 
along with some useful information to the user list.

I will close this issue as its not a bug report.
