### ISSUE TITLE
AsteriskPBX.performPostCreationTasks(AsteriskPBX.java:118) NullPointerException

### ISSUE THREAD

**Issue by ElPadre1978** [asterisk-java/asterisk-java#280] opened 2018-12-05 23:01 UTC
Hi,
i tried your github example "blindTransfer" and got always an NullPointerException. Here is my trace:

Exception in thread "main" java.lang.NullPointerException
	at org.asteriskjava.pbx.internal.core.AsteriskPBX.performPostCreationTasks(AsteriskPBX.java:118)
	at org.asteriskjava.pbx.PBXFactory.init(PBXFactory.java:21)
	at com.asteriskcall.MyMain.main(MyMain.java:39)

My Java version is:
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

I can TCP ping my Asterisk box port 5038 and saw with networkmonitor, that my asterisk-java app does nothing with my Asterisk.

Are there any special settings to set or do i overlook something? 

Thanks for your help.

**Comment by omidshapouri** [comment] 2019-03-03 10:21
Any update on this issue?

**Comment by bsutton** [comment] 2019-03-03 22:18
Have you check the logs. Looks to me like the AsteriskPBX constructor is throwing a exception which will be logged.

**Comment by rlsutton1** [comment] 2019-03-03 22:48
I've just committed a change to master which should help to make it more obvious where the problem is.

Please checkout master, try again and post the logs back here.

**Closed** 2022-11-13 08:11 UTC
Labels: kind/question
